#!/usr/bin/env zsh

# boot2docker
## main
alias bd='boot2docker'

## misc
alias bdsi='eval $(boot2docker shellinit 2>/dev/null)'
alias bdup='boot2docker up'
alias bdre='boot2docker restart'
alias bdsh='boot2docker ssh'
alias bdip='boot2docker ip'
