#!/usr/bin/env zsh

# boot2docker
## main
alias bd='boot2docker'

## misc
alias bdsi='eval $(bd shellinit 2>/dev/null)'
alias bdup='bd up'
alias bdre='bd restart'
alias bdsh='bd ssh'
alias bdip='bd ip'
