#!/usr/bin/env zsh

# docker
## remove existing git aliases
elunalias docker dk
alias dk='docker'

## ps
alias dkp='docker ps'
alias dkpa='docker ps -a'
alias dkpaq='docker ps -a -q'

## rm
alias dkrm='docker rm'
alias dkrmf='docker rm -f'

## images
alias dki='docker images'
alias dkiq='docker images -q'

## rmi
alias dkrmi='docker rmi'
alias dkrmif='docker rmi -f'

## build
alias dkb='docker build'
alias dkbt='docker build -t'

## run
alias dkr='docker run -it'
alias dkrr='docker run -it --rm'

## exec
alias dke='docker exec -it'

## idioms
alias dkclean='dkrmf $(dkpaq)'
