#!/usr/bin/env zsh

# git
## remove existing git aliases
elunalias git

## add
alias ga='git add'
alias gap='git add --patch'
alias gai='git add --interactive'
alias gaa='git add --all'

## pull
alias gp='git pull'
alias gpr='git pull --rebase=true'

## diff
alias gd='git diff'
alias gdc='git diff --cached'

## fetch
alias gf='git fetch'
alias gfa='git fetch --all'
alias gfp='git fetch --prune'
alias gft='git fetch --tags'
alias gfapt='git fetch --all; git fetch --prune; git fetch --tags'

## merge
alias gg='git merge'
alias ggnf='git merge --no-ff'

## status
alias gs='git status --short --branch'
alias gsl='git status --long --branch'

## reset
alias ge='git reset'
alias geh='git reset --hard'
alias geh0='git reset --hard HEAD'
alias geh1='git reset --hard HEAD~1'
alias geh2='git reset --hard HEAD~2'
alias geh3='git reset --hard HEAD~3'

## rebase
alias gr='git rebase'
alias gri='git rebase --interactive'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grs='git rebase --skip'

## push
alias gu='git push'
alias guu='git push -u'

## log
alias gl='git log'
alias glm='git log --pretty=%B'
alias glml='git log --pretty=%B -1 |head -n1'

## commit
alias gc='git commit'
alias gcm='git commit --message'
alias gaacm='git commit --all --message'
alias gaacam='git commit --all --amend'

## checkout
alias go='git checkout'
alias gob='git checkout -b'

## branch
alias gb='git branch'
alias gbl='git branch --list --all --verbose --verbose'

## remote
alias gm='git remote'
alias gml='git remote --verbose'
alias gma='git remote add'
alias gmr='git remote remove'
alias gmn='git remote rename'
alias gmu='git remote set-url'

## stash
alias gt='git stash'
alias gtp='git stash pop'
alias gtl='git stash list'
alias gta='git stash apply'
