#!/usr/bin/env zsh

# misc
## composer
alias cou='composer update'
alias coi='composer install'

## terminal multiplexer
alias ta='tmux attach'
alias sr='screen -R'

## ps/pgrep
alias px='ps aux|grep'
alias pgr='pgrep -il'

## tree/ls/k
alias tree='tree -Ffip --dirsfirst'
alias l='ls -la'
alias k='k -ah'

## grep
alias unco='egrep -v "^ *($|[;#])"'
