#!/usr/bin/env zsh

# vagrant
## remove existing git aliases
elunalias vagrant

## base
alias vagrant='VAGRANT_CWD=$(ls -d vagrant 2>/dev/null || echo ''.'') vagrant'

## up
alias vu='vagrant up'
alias vunp='vu --no-provision'

## provision
alias vp='vagrant provision'
alias vpp='vp --provision-with=puppet'

## status
alias vt='vagrant status'
alias vtg='vagrant global-status'

## reload
alias vr='vagrant reload'
alias vrp='vr --provision'

## ssh
alias vs='vagrant ssh'
alias vsc='vs -c'

## destroy
alias vd='vagrant destroy'
alias vdf='vd -f'

## halt
alias vh='vagrant halt'

## suspend
alias vz='vagrant suspend'
